# 服务器配置
server:
  host: "0.0.0.0"
  port: 7768

# 本地调试测试时打开
environment: development
# environment: production

client:
  host: localhost
  port: 5173

# 数据库配置
database:
  host: "117.147.37.7"
  port: 3772
  user: "danmuapi"
  password: "jisi9Lnfr&CyJ4"
  name: "danmuapi"
# JWT (JSON Web Token) 配置
jwt:
  secret_key: "your_super_secret_key_for_jwt_please_change_it" # 请务必修改为一个复杂且唯一的密钥, 建议通过环境变量覆盖
  algorithm: "HS256"
  access_token_expire_minutes: 1440 # 令牌有效期（分钟），例如 1天
